[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = true
preview = true

[tool.ruff]
line-length = 100
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "UP", # pyupgrade
    "D",  # pydocstyle
    "C",  # mccabe complexity
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
# Ignore missing docstrings in tests
"tests/*" = ["D"]
