{
 "title": "Track Dashboard",
 "time": { "from": "2018-05-09T04:47:07.620Z", "to": "2018-05-09T04:47:28.964Z" },
 "panels": [
  {
   "title": "Tracking Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "error_blind",
     "query": "SELECT mean(\"error_ra\") AS \"blind RA\", mean(\"error_dec\") AS \"blind DEC\" FROM \"error_blind\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "error_ra" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "blind RA" ], "type": "alias" }
      ],
      [
       { "params": [ "error_dec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "blind DEC" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "error_optical",
     "query": "SELECT mean(\"error_ra\") AS \"optical RA\", mean(\"error_dec\") AS \"optical DEC\" FROM \"error_optical\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "error_ra" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "optical RA" ], "type": "alias" }
      ],
      [
       { "params": [ "error_dec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "optical DEC" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "error_hybrid",
     "query": "SELECT mode(\"state\") AS \"hybrid state\" FROM \"error_hybrid\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mode"
       },
       { "params": [ "hybrid state" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Slew Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tracker",
     "query": "SELECT mean(\"rate_ra\") AS \"rate RA\", mean(\"rate_dec\") AS \"rate DEC\" FROM \"tracker\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rate_ra" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rate RA" ], "type": "alias" }
      ],
      [
       { "params": [ "rate_dec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "rate DEC" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tracker",
     "query": "SELECT mean(\"loop_filt_int_ra\") AS \"integrator RA\", mean(\"loop_filt_int_dec\") AS \"integrator DEC\" FROM \"tracker\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "loop_filt_int_ra" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "integrator RA" ], "type": "alias" }
      ],
      [
       { "params": [ "loop_filt_int_dec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "integrator DEC" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gamepad",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gamepad",
     "query": "SELECT mean(\"left_x\") AS \"left x\", mean(\"left_y\") AS \"left y\" FROM \"gamepad\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "left_x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "left x" ], "type": "alias" }
      ],
      [
       { "params": [ "left_y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "left y" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gamepad",
     "query": "SELECT mean(\"right_x\") AS \"right x\", mean(\"right_y\") AS \"right y\" FROM \"gamepad\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "right_x" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "right x" ], "type": "alias" }
      ],
      [
       { "params": [ "right_y" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "right y" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Tracking State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "error_hybrid",
     "query": "SELECT last(\"state\") FROM \"error_hybrid\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}