# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and Test

on:
  push:
    branches: [ github-actions ]
  pull_request:
    branches: [ github-actions ]
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install numpy  # required until https://github.com/seeing-things/zwo/issues/66 is resolved
        pip install .
    - name: Lint with pylint
      run: |
        pylint track/

  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy  # required until https://github.com/seeing-things/zwo/issues/66 is resolved
        pip install .
    - name: Run unit tests
      run: |
        python3 -m unittest
